services:
  redis:
    image: redis:7-alpine
    container_name: simple-dep-cache-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: unless-stopped