name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run unit tests (without Redis)
      run: uv run pytest -m "not redis_e2e"

  test-redis-e2e:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10ms
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run Redis e2e tests
      run: uv run pytest -m redis_e2e
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        REDIS_DB: 0
        DEP_CACHE_ENABLED: "true"

